# Generated by Django 3.2.5 on 2021-07-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emaiil',
            new_name='email',
        ),
    ]
